### ISSUE TITLE
Photos support [MVP]

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#487]
- [x] Allow photo to be taken and added to observation
- [x] Show thumbnail on add/edit observation form
- [x] Photo uploaded in background
- [x] Integrated notifications
- [ ] Allow adding multiple photos (#454)
- [x] Delete unused/removed photos (#455) 

@shobhitagarwal1612 please cmiiw.
